---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-acl-job
spec:
  destination:
    namespace: vault
    server: https://kubernetes.default.svc
  project: default
  source:
    path: applications/vault-acl-job/development
    repoURL: git@github.com:adzuci/kubernetes.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
