nginx-ingress:
  controller:
    ingressClass: public
    publishService: 
      enabled: true
    extraArgs:
      enable-ssl-passthrough: ""
    resources:
      limits:
        cpu: 100m
        memory: 250Mi
      requests:
        cpu: 50m
        memory: 100Mi
  defaultBackend:
    resources:
      limits:
        cpu: 100m
        memory: 250Mi
      requests:
        cpu: 50m
        memory: 100Mi
