nginx-ingress:
  controller:
    ingressClass: public   # Only implement ingresses that are explicitly marked as public
    publishService: 
      enabled: true   # required for external-dns to map elb ingresses to dns names
    extraArgs:
      enable-ssl-passthrough: ""
    resources:
      limits:
        cpu: 100m
        memory: 250Mi
      requests:
        cpu: 50m
        memory: 100Mi
  defaultBackend:
    resources:
      limits:
        cpu: 100m
        memory: 250Mi
      requests:
        cpu: 50m
        memory: 100Mi
