---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github-webhook-ingress-manifests
spec:
  destination:
    namespace: github-webhook-ingress
    server: https://kubernetes.default.svc
  project: default
  source:
    path: applications/github-webhook-ingress/manifests
    repoURL: git@github.com:adzuci/kubernetes.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github-webhook-ingress
  labels:
    deployMethod: helm
spec:
  destination:
    namespace: github-webhook-ingress
    server: https://kubernetes.default.svc
  project: default
  source:
    path: applications/github-webhook-ingress
    repoURL: git@github.com:adzuci/kubernetes.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  ignoreDifferences:
  - kind: Service
    jsonPointers:
    - /spec/clusterIP
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
