---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
type: kubernetes.io/tls
data:
  # This password is hashed with bcrypt via https://www.devglan.com/online-tools/bcrypt-hash-generator & then echo'd to `| base64`
  # Check out https://howchoo.com/g/ywvlmgnmode/read-kubernetes-secrets to read it               .
  admin.password: YS9XMXN2eGVDZ2Y3dUhmYW1WNFguTFpkcXlHdnhxWE0wVG5zYWhlCg==
  admin.passwordMtime: MjAyMC0wOC0wM1QwMDo1Nzo1NUVEVA==

stringData:
  # Probably need to rotate this or pull it from a different place.
  # Since we only plan to use it to verify Github webhook triggers it should be safe enough.  
  webhook.github.secret: "HvqVzVHmxY4sa15Tn0253fjV"
