---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
type: kubernetes.io/tls
data:
  # This password is hashed with bcrypt                    .
  admin.password: fkrmfknefljjnergnwljntej vjlWETGTRGBWbwrtbgWRTgrTGwrtgwrtgWRtgWRTgwtrG45g4revev3
  admin.passwordMtime: njnjrnjncjnrkrfefreferfefrf=

stringData:
  # Not sure how to deal with this in a public repo 
  webhook.github.secret: "<hook>"
