---
apiVersion: v1
kind: Secret
metadata:
  name: prod-dyhedral-eks-cluster
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: prod-dyhedral-eks
  server: https://AC0DE220CE137EC2DE6BE28E10A64D07.gr7.us-east-1.eks.amazonaws.com
  config: |
    {
      "awsAuthConfig": {
        "clusterName": "prod-dyhedral-eks"
      },
      "tlsClientConfig": {
        "insecure": false,
        "caData": "<data>"
      }
    }
