resources:
- ../base
- argocd-ingress.yaml
- cluster-secret-prod-dyhedral.yaml
patches:
  - path: argocd-cm.yaml
  - path: argocd-rbac-cm.yaml
  - path: argocd-secret.yaml
  - path: argocd-application-controller-sa.yaml
  - path: argocd-application-controller-deployment.yaml
  - path: argocd-server-sa.yaml
  - path: argocd-server-deployment.yaml
