---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server-manifests
spec:
  destination:
    namespace: metrics-server
    server: https://kubernetes.default.svc
  project: default
  source:
    path: applications/metrics-server/manifests
    repoURL: git@github.com:adzuci/kubernetes.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  labels:
    deployMethod: helm
spec:
  destination:
    namespace: metrics-server
    server: https://kubernetes.default.svc
  project: default
  source:
    path: applications/metrics-server
    repoURL: git@github.com:adzuci/kubernetes.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
