---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-state-metrics-manifests
spec:
  destination:
    namespace: kube-state-metrics
    server: https://kubernetes.default.svc
  project: default
  source:
    path: applications/kube-state-metrics/manifests
    repoURL: git@github.com:adzuci/kubernetes.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-state-metrics
  labels:
    deployMethod: helm
spec:
  destination:
    namespace: kube-state-metrics
    server: https://kubernetes.default.svc
  project: default
  source:
    path: applications/kube-state-metrics
    repoURL: git@github.com:adzuci/kubernetes.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
