---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atlantis-manifests
spec:
  destination:
    namespace: atlantis
    server: https://kubernetes.default.svc
  project: default
  source:
    path: applications/atlantis/manifests
    repoURL: git@github.com:adzuci/kubernetes.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atlantis
spec:
  destination:
    namespace: atlantis
    server: https://kubernetes.default.svc
  project: default
  source:
    path: applications/atlantis
    repoURL: git@github.com:adzuci/kubernetes.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
