---
apiVersion: v1
kind: ConfigMap
metadata:
  name: consul-template-config
data:
  config.hcl: |
    "vault" = {
      "vault_agent_token_file" = "/vault/secrets/.vault-token"
      "renew_token" = false
    }
    template {
      source = "/consul-template-config/.env.hcl"
      destination = "/vault/secrets/.env"
    }
  .env.hcl: |
    {{ with secret "kv/mass-testing-platform" }}
    APP_ENV=prod
    DEBUG_MODE=false

    # App specific configurations in json format
    APP_CONFIG=

    # AWS credentials - can be found when logging onto awsconsole/
    AWS_ACCESS_KEY_ID=
    AWS_SECRET_ACCESS_KEY=
    AWS_SESSION_TOKEN=

    # Emails will be sent from here
    SES_EMAIL_ADDRESS=adam@blackwell.ai
    SES_EMAIL_NAME=COVID Test

    EMAIL_LOG_LEVEL=0

    # Health Network SMTPS credentials
    HEALTH_NETWORK_USER_NAME=
    HEALTH_NETWORK_USER_PWD=
    HEALTH_NETWORK_MAIL_FROM=
    HEALTH_NETWORK_MAIL_TO=
    HEALTH_NETWORK_SMTP_URL=
    HEALTH_NETWORK_SMTP_PORT=

    # SFTP login credentials to transmit CSVs
    PRINT_SFTP_HOST=
    PRINT_SFTP_USERNAME=
    PRINT_SFTP_PASSWORD=

    # NeverBounce: 3rd party email validation service
    NEVERBOUNCE_API_KEY=

    # Google Maps API
    GOOGLE_MAPS_API_KEY={{ .Data.data.GOOGLE_MAPS_API_KEY }}

    # Webhook to send metrics data on created appointments
    METRICS_WEBHOOK_URL=

    ## LEAVE EVERYTHING ALONE UNDER THIS LINE #######
    #################################################
    DB_USERNAME=easyapp
    DB_NAME=easyapp

    # before deploying to production change to harder password, and don't commit it to git
    DB_PASSWORD=veryhardpassword

    # change to your installation address
    APP_URL=localhost
    APP_HOST=0.0.0.0
    APP_PORT=80

    # email settings - set to 'smtp' and provide SMTP settings if you want to send emails
    EMAIL_PROTOCOL=mail
    SMTP_HOST=smtp.gmail.com
    SMTP_USER=user
    SMTP_PASS=password
    SMTP_CRYPTO=ssl
    SMTP_PORT=25
    {{ end }}
