---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  source:
    path: applications/cert-manager/prod
    repoURL: git@github.com:adzuci/kubernetes.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  # https://github.com/argoproj/argoproj-deployments/blob/master/argoproj/base/cert-manager.yaml
  ignoreDifferences:
  - group: apiextensions.k8s.io
    jsonPointers:
    - /status
    - /spec
    kind: CustomResourceDefinition

