---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-acl-job
  namespace: vault
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-acl-job
  namespace: vault
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vault-acl-job
      app.kubernetes.io/instance: vault-acl-job
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vault-acl-job
        app.kubernetes.io/instance: vault-acl-job
    spec:
      volumes:
        - name: vault-auth
          emptyDir:
            medium: Memory
        - name: vault-acl-job-cm
          configMap:
            name: vault-acl-job-cm
            defaultMode: 0550
      initContainers:
      - name: vault-authenticator
        image: adzuci/vault-kubernetes-authenticator:latest
        imagePullPolicy: Always
        # command: [ "/bin/sh", "-c", "--" ]
        # args: [ "while true; do echo \"ka thump\"; sleep 30; done;" ]
        volumeMounts:
        - name: vault-auth
          mountPath: /var/run/secrets/vaultproject.io
        env:
        - name: VAULT_ROLE
          valueFrom:
            configMapKeyRef:
              key: VAULT_ROLE
              name: vault-acl-job-cm
        - name: VAULT_ADDR
          valueFrom:
            configMapKeyRef:
              key: VAULT_ADDR
              name: vault-acl-job-cm
        securityContext:
          allowPrivilegeEscalation: false
      containers:
      - name: vault-acl-job
        image: vault:latest
        env:
        - name: VAULT_ROLE
          valueFrom:
            configMapKeyRef:
              key: VAULT_ROLE
              name: vault-acl-job-cm
        - name: VAULT_ADDR
          valueFrom:
            configMapKeyRef:
              key: VAULT_ADDR
              name: vault-acl-job-cm
        - name: HOME
          value: /home/vault
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "while true; do /vault-acl-job-cm/acls.sh; sleep 120; done;" ]
        volumeMounts:
        - name: vault-acl-job-cm
          mountPath: /vault-acl-job-cm
        - name: vault-auth
          mountPath: /home/vault
        resources:
          limits:
            cpu: 100m
            memory: 512Mi
          requests:
            cpu: 25m
            memory: 512Mi
      serviceAccount: vault-acl-job
