---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-autoscaler-manifests
spec:
  destination:
    namespace: cluster-autoscaler
    server: https://kubernetes.default.svc
  project: default
  source:
    path: applications/cluster-autoscaler/manifests
    repoURL: git@github.com:adzuci/kubernetes.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-autoscaler
  labels:
    deployMethod: helm
spec:
  destination:
    namespace: cluster-autoscaler
    server: https://kubernetes.default.svc
  project: default
  source:
    path: applications/cluster-autoscaler
    repoURL: git@github.com:adzuci/kubernetes.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  ignoreDifferences:
  - kind: Service
    jsonPointers:
    - /spec/clusterIP
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
