---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
type: Opaque
data:
  # This is the development password, which is "admin"
  admin.password: JDJhJDEwJGRlcTZnWXFHWTNoTTlBbTBPQWI3emU3UnFYN01PejVNRGJLeEJnaTRyMW03czVyY2NXTnFl
  admin.passwordMtime: MjAyMC0wMS0yM1QxODo1MTo1MFo=
