---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/clusters/development
    repoURL: git@github.com:adzuci/kubernetes.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
