resources:
- applications.yaml

bases:
- ../../../applications/argocd/install
- ../../../applications/vault/install
- ../../../applications/vault-development-bootstrapper/install
- ../../../applications/vault-acl-job/development/install
- ../../../applications/metrics-server/install
- ../../../applications/kube-state-metrics/install
- ../../../applications/cert-manager-resources/development/install
- ../../../applications/cert-manager/development/install
- ../../../applications/public-ingress/install


patchesStrategicMerge:
- argocd.yaml

namePrefix: development-

# What branch should this cluster use for ALL applications AND the root pipeline
# the install/branch.yaml is shared between the root pipeline and the application pipelines
patches:
- target:
    group: argoproj.io
    version: v1alpha1
    kind: Application
  path: branch.yaml

# What values.yaml should this cluster use for ALL HELM applications
- target:
    group: argoproj.io
    version: v1alpha1
    kind: Application
    labelSelector: deployMethod=helm
  patch: |-
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: not-relevant-to-patch
        namespace: argocd
      spec:
        source:
          helm:
            valueFiles:
            - values.yaml
            - development.yaml

# What EKS cluster to install into
- target:
    group: argoproj.io
    version: v1alpha1
    kind: Application
  patch: |-
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: not-relevant-to-patch
        namespace: argocd
      spec:
        destination:
          server: 'https://kubernetes.default.svc'

# Set the finalizer so that cascade deletes are default since we do not store data in the cluster
- target:
    group: argoproj.io
    version: v1alpha1
    kind: Application
  patch: |-
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: not-relevant-to-patch
        namespace: argocd
        finalizers:
          - resources-finalizer.argocd.argoproj.io
