bases:
- github.com/argoproj/argo-cd/manifests/cluster-install?ref=v1.3.6
resources:
  - argocd-ns.yaml
  - argocd-deploy-key.yaml
patchesStrategicMerge:
  - argocd-cm.yaml
  - argocd-deployments-image.yaml
namespace: argocd
